"""E2E: SB-01 → SB-09 전체 흐름을 모바일 화면(390×844)으로 돌리며 화면마다 스크린샷.
실행: (백엔드 8000 실행 중) python e2e/flow.py [BASE_URL] [OUT_DIR]"""
import sys, re
from playwright.sync_api import sync_playwright, expect

BASE = sys.argv[1] if len(sys.argv) > 1 else "http://127.0.0.1:8000/"
OUT = sys.argv[2] if len(sys.argv) > 2 else "e2e/shots"
errors = []

def shot(page, name):
    page.wait_for_timeout(250)
    page.screenshot(path=f"{OUT}/{name}.png", full_page=False)
    page.screenshot(path=f"{OUT}/{name}_full.png", full_page=True)

with sync_playwright() as p:
    b = p.chromium.launch()
    ctx = b.new_context(viewport={"width": 390, "height": 844}, device_scale_factor=2, locale="ko-KR")
    page = ctx.new_page()
    page.on("console", lambda m: errors.append(f"console.{m.type}: {m.text}") if m.type in ("error",) else None)
    page.on("pageerror", lambda e: errors.append(f"pageerror: {e}"))
    page.goto(BASE)
    expect(page.get_by_text("MIRI").first).to_be_visible()
    # SB-01 시작(로그인 없음): 사용자 유형은 이 브라우저에 남는다
    page.get_by_role("button", name="자영업자").click()
    page.reload()
    expect(page.get_by_role("button", name="자영업자")).to_have_attribute("aria-pressed", "true")
    page.get_by_role("button", name="예비창업자").click()
    shot(page, "sb01_start")
    page.get_by_role("button", name="분석 시작").click()
    expect(page.get_by_role("heading", name="상권 선택")).to_be_visible()
    page.get_by_label("지역·상권 검색").fill("강남역")
    page.get_by_role("option").first.wait_for()
    page.get_by_role("option").first.click()
    page.get_by_text("강남역이 있는 구").wait_for()                     # 카드 제목은 구 이름(구 전체 합계라서)
    shot(page, "sb02_area")
    # UC-02 후보 비교: 같은 기준으로 나란히, 업종을 고르면 그 업종의 위험·매출까지
    page.get_by_role("button", name=re.compile("후보 \\d곳 (중 \\d곳 )?비교")).click()
    cmp = page.get_by_role("dialog", name="후보 지역 비교")
    cmp.locator("table.cmp").wait_for()
    cmp.get_by_label("업종별로 보기 (선택)").select_option(label="커피-음료")
    cmp.get_by_text("커피-음료 폐업 위험").wait_for()
    assert cmp.locator("thead th").count() >= 3, "후보 2곳 이상이 열로 나와야"
    shot(page, "sb02_compare")
    page.keyboard.press("Escape")
    page.get_by_role("button", name=re.compile("(으로|로) 분석$")).click()

    expect(page.get_by_role("heading", name="창업 조건 입력")).to_be_visible()
    page.get_by_role("button", name="다음").click()                    # 빈 값 → 검증 메시지
    expect(page.get_by_text("총 창업 예산을 입력해 주세요")).to_be_visible()
    page.locator("#budget").fill("8000")
    page.locator("#rent").fill("300.5")                                 # 소수 입력이 10배로 바뀌지 않아야
    assert page.locator("#rent").input_value() == "300.5", page.locator("#rent").input_value()
    page.locator("#rent").fill("300")
    page.locator("#labor").fill("250")
    shot(page, "sb03_conditions")
    page.get_by_role("button", name="다음").click()

    expect(page.get_by_role("heading", name="관심 업종 선택")).to_be_visible()
    page.get_by_role("button", name=re.compile("카페·디저트")).click()
    page.get_by_role("button", name=re.compile("분식·간이음식")).click()
    shot(page, "sb04_interests")
    page.get_by_role("button", name="분석 시작").click()

    expect(page.get_by_role("heading", name="추천 결과")).to_be_visible()
    page.get_by_text("적합도 점수").first.wait_for()
    expect(page.get_by_text(re.compile("전체\\(자치구\\) 기준으로 분석했어요"))).to_be_visible()   # 분석 단위 안내는 맨 위
    shot(page, "sb05_results")
    # 관심 업종(커피-음료) 선택 후 위험도
    page.get_by_role("button", name=re.compile("커피-음료")).first.click()
    page.get_by_role("button", name="상세 위험도 보기").click()
    expect(page.get_by_role("heading", name="폐업 위험도")).to_be_visible()
    page.get_by_text("주요 위험 요인").wait_for()
    shot(page, "sb06_risk")

    page.get_by_role("button", name="손익분기").click()
    expect(page.get_by_role("heading", name="손익분기점")).to_be_visible()
    page.get_by_text("손해 보지 않으려면 매달 필요한 매출").wait_for()
    shot(page, "sb07_breakeven")
    # 입력값 수정 → 목표 월수입 300만, 객단가 9,000 (시트가 열리면 포커스가 시트로, 라벨로 칸을 찾을 수 있어야)
    page.get_by_role("button", name="수정").click()
    dlg = page.get_by_role("dialog", name="입력값 수정")
    dlg.wait_for()
    dlg.get_by_label("목표 월수입 (대표자)").fill("300")
    dlg.get_by_label("객단가").fill("9000")
    page.get_by_role("button", name="다시 계산").click()
    page.get_by_text("목표 월수입 300만원 포함").wait_for()
    page.get_by_text("목표 월수입까지 벌려면 매달 필요한 매출").wait_for()
    shot(page, "sb07_breakeven_edited")

    hero = page.locator(".hero .big").inner_text()
    page.get_by_role("button", name="리포트에 반영").click()
    expect(page.get_by_role("heading", name="액션 리포트")).to_be_visible()
    page.get_by_text("한줄 결론", exact=True).wait_for()
    shot(page, "sb08_report")
    # 리포트의 손익분기 카드 → 반영했던 계산(수정값)이 그대로 열려야
    page.get_by_role("button", name=re.compile("(손익분기|필요) 월매출")).click()
    page.get_by_text("목표 월수입까지 벌려면 매달 필요한 매출").wait_for()
    assert page.locator(".hero .big").inner_text() == hero, (page.locator(".hero .big").inner_text(), hero)
    page.go_back()
    page.get_by_text("한줄 결론", exact=True).wait_for()
    # 리포트 → 위험도 → 손익분기도 리포트에 반영한 계산을 열고, '분석 조건으로'로 되돌릴 수 있어야
    page.get_by_role("button", name=re.compile("폐업 위험")).first.click()
    page.get_by_text("주요 위험 요인").wait_for()
    page.get_by_role("button", name="손익분기").click()
    page.get_by_text("리포트에 반영한 값이에요").wait_for()
    assert page.locator(".hero .big").inner_text() == hero, ("재방문", page.locator(".hero .big").inner_text(), hero)
    page.get_by_role("button", name="분석 조건으로").click()
    page.get_by_text("손해 보지 않으려면 매달 필요한 매출").wait_for()
    page.get_by_role("button", name="리포트에 반영").click()
    page.get_by_text("한줄 결론", exact=True).wait_for()

    # 로그인 없이 바로 저장 → 이 브라우저의 저장 목록(새로고침해도 남아 있어야)
    page.get_by_role("button", name="리포트 저장").click()
    page.get_by_text("리포트를 저장했어요").wait_for()
    expect(page.get_by_role("button", name="저장 리포트 보기")).to_be_visible()
    page.get_by_role("button", name="저장 리포트 보기").click()
    expect(page.get_by_role("heading", name="저장 리포트")).to_be_visible()
    page.get_by_text("이 브라우저에 저장한 리포트 1건").wait_for()
    page.reload()
    page.get_by_text("이 브라우저에 저장한 리포트 1건").wait_for()

    # 두 번째 분석: 홍대입구역 1km, 고수익형, 한식 → 저장
    page.get_by_role("button", name="새 분석 시작").click()
    page.get_by_label("지역·상권 검색").fill("홍대")
    page.get_by_label("지역·상권 검색").press("Enter")                  # 결과가 오기 전 Enter → 이 검색어의 첫 결과(이전 결과 아님)
    page.get_by_role("button", name="1km").click()
    page.get_by_text("홍대입구역이 있는 구").wait_for()
    page.get_by_role("button", name=re.compile("(으로|로) 분석$")).click()
    page.locator("#budget").fill("12000")
    page.locator("#rent").fill("400")
    page.locator("#labor").fill("600")
    page.get_by_role("radio", name="고수익형").click()
    page.get_by_role("button", name="다음").click()
    page.get_by_role("button", name=re.compile("한식·백반")).click()
    page.get_by_role("button", name="분석 시작").click()
    page.get_by_text("적합도 점수").first.wait_for()
    page.get_by_role("button", name="상세 위험도 보기").click()
    page.get_by_role("button", name="대응 액션 보기").click()
    page.get_by_text("한줄 결론", exact=True).wait_for()
    page.get_by_role("button", name="리포트 저장").click()
    page.get_by_text("리포트를 저장했어요").wait_for()
    page.get_by_role("button", name="저장 리포트 보기").click()
    page.get_by_text("저장한 리포트 2건").wait_for()
    # 저장 리포트 메모(ERD saved_reports.memo)
    page.get_by_role("button", name=re.compile("리포트.* 메모 쓰기")).first.click()
    page.get_by_role("dialog", name="메모").get_by_label("메모 내용").fill("평일 점심 현장 확인 필요")
    page.get_by_role("button", name="메모 저장").click()
    page.get_by_text("메모: 평일 점심 현장 확인 필요").wait_for()
    shot(page, "sb09_saved")
    # 저장 리포트 삭제(확인 시트 → 목록에서 빠지고 오류 없이 '삭제했어요')
    page.get_by_role("button", name=re.compile("리포트.* 삭제")).first.click()
    dlg = page.get_by_role("dialog", name="리포트 삭제")
    dlg.get_by_text("메모도 함께 지워져요").wait_for()
    dlg.get_by_role("button", name="삭제", exact=True).click()
    page.get_by_text("삭제했어요").wait_for()
    page.get_by_text("저장한 리포트 1건").wait_for()
    # 다른 브라우저(저장소가 다른 새 사용자)에는 이 목록이 보이지 않는다
    other = b.new_context(viewport={"width": 390, "height": 844}, locale="ko-KR").new_page()
    other.goto(BASE + "#/reports")
    other.get_by_text("이 브라우저에 저장한 리포트 0건").wait_for()
    # 여럿이 쓰는 컴퓨터 정리: 이 브라우저의 저장 목록 모두 지우기(로그아웃 대신)
    page.get_by_role("button", name="이 브라우저의 저장 목록 모두 지우기").click()
    wipe = page.get_by_role("dialog", name="저장 목록 모두 지우기")
    wipe.get_by_text("저장한 리포트 1건과 메모를").wait_for()
    wipe.get_by_role("button", name="모두 지우기", exact=True).click()
    page.get_by_text("저장 목록을 모두 지웠어요").wait_for()
    page.get_by_text("이 브라우저에 저장한 리포트 0건").wait_for()
    b.close()

print("E2E OK")
if errors:
    print("브라우저 오류:", *errors, sep="\n  ")
    sys.exit(1)
